### PR TITLE
Added gulp functionality to update based off CSS 

### PR DESCRIPTION
**Pull request by stevenshuhyow**

### CODE REVIEW

**Comment by kevhuang** [comment]
Did you intend to include the changes you made for the routes for team and contact? As of now, the Gulp build is not working.

Also, I'm not sure if we want to show the "Powered By" footer on every component other than the main landing page. I prefer to have that only show on the landing page when you're not logged in.

What are the rest of the team's thoughts?

**Comment by stevenshuhyow** [comment]
@kevhuang  Yeah I removed it a couple minutes ago.  Well, just let me know.  I'm going to start working on getting pictures in there

**Comment by ekong2** [comment]
+1 on "powered by" only being on the front page.

**Comment by dmsakamoto** [comment]
Done in #218

**Pull request closed without merging**
